from extensions import db
from datetime import datetime


# ─────────────────────────────────────────────────────────────────────────────
class ClinicalNote(db.Model):
    """Uploaded clinical document / typed note."""
    __tablename__ = "clinical_notes"

    id             = db.Column(db.Integer,     primary_key=True)
    patient_id     = db.Column(db.Integer,     db.ForeignKey("patients.id"), nullable=False, index=True)
    doctor_id      = db.Column(db.Integer,     db.ForeignKey("users.id"),    nullable=False)
    visit_type     = db.Column(db.String(50),  default="Initial Consultation")

    # Source: file upload OR typed text
    source_type    = db.Column(db.String(10),  default="text")   # text | file
    raw_text       = db.Column(db.Text,        nullable=True)     # typed or extracted text

    # Azure Blob Storage
    file_name      = db.Column(db.String(255), nullable=True)
    blob_url       = db.Column(db.String(500), nullable=True)     # Azure Blob public/SAS URL
    blob_name      = db.Column(db.String(255), nullable=True)     # Unique blob name in container

    # Azure Document Intelligence (OCR)
    ocr_text       = db.Column(db.Text,        nullable=True)

    # Processing options (stored as flags)
    use_soap       = db.Column(db.Boolean,     default=True)
    use_diagnosis  = db.Column(db.Boolean,     default=True)
    use_treatment  = db.Column(db.Boolean,     default=True)
    use_risk       = db.Column(db.Boolean,     default=False)
    model_choice   = db.Column(db.String(30),  default="MediAI Pro")

    processed      = db.Column(db.Boolean,     default=False)
    created_at     = db.Column(db.DateTime,    default=datetime.utcnow)

    # Relationship to summary
    summary        = db.relationship("AISummary", backref="note", uselist=False)

    def to_dict(self):
        return {
            "id":          self.id,
            "patient_id":  self.patient_id,
            "visit_type":  self.visit_type,
            "source_type": self.source_type,
            "file_name":   self.file_name,
            "blob_url":    self.blob_url,
            "processed":   self.processed,
            "created_at":  self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
class AISummary(db.Model):
    """SOAP note generated by Azure AI Language Service."""
    __tablename__ = "ai_summaries"

    id           = db.Column(db.Integer, primary_key=True)
    note_id      = db.Column(db.Integer, db.ForeignKey("clinical_notes.id"), nullable=False, index=True)
    patient_id   = db.Column(db.Integer, db.ForeignKey("patients.id"),       nullable=False, index=True)
    doctor_id    = db.Column(db.Integer, db.ForeignKey("users.id"),          nullable=False)

    # SOAP sections (stored individually for easy tab rendering)
    subjective   = db.Column(db.Text, nullable=True)
    objective    = db.Column(db.Text, nullable=True)
    assessment   = db.Column(db.Text, nullable=True)
    plan         = db.Column(db.Text, nullable=True)

    # Azure extras
    key_phrases  = db.Column(db.Text,    nullable=True)   # JSON list
    entities     = db.Column(db.Text,    nullable=True)   # JSON list
    risk_score   = db.Column(db.String(10), nullable=True)

    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        import json
        return {
            "id":          self.id,
            "note_id":     self.note_id,
            "patient_id":  self.patient_id,
            "subjective":  self.subjective,
            "objective":   self.objective,
            "assessment":  self.assessment,
            "plan":        self.plan,
            "key_phrases": json.loads(self.key_phrases) if self.key_phrases else [],
            "entities":    json.loads(self.entities)    if self.entities    else [],
            "risk_score":  self.risk_score,
            "created_at":  self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
class Appointment(db.Model):
    """Patient appointment."""
    __tablename__ = "appointments"

    id           = db.Column(db.Integer,     primary_key=True)
    patient_id   = db.Column(db.Integer,     db.ForeignKey("patients.id"), nullable=False, index=True)
    doctor_id    = db.Column(db.Integer,     db.ForeignKey("users.id"),    nullable=False)
    title        = db.Column(db.String(150), nullable=False)
    visit_type   = db.Column(db.String(50),  default="Follow-Up")
    scheduled_at = db.Column(db.DateTime,    nullable=False)
    duration_min = db.Column(db.Integer,     default=30)
    status       = db.Column(db.String(20),  default="scheduled")   # scheduled | completed | cancelled
    notes        = db.Column(db.Text,        nullable=True)
    created_at   = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":           self.id,
            "patient_id":   self.patient_id,
            "patient_name": self.patient.name if self.patient else None,
            "title":        self.title,
            "visit_type":   self.visit_type,
            "scheduled_at": self.scheduled_at.isoformat(),
            "duration_min": self.duration_min,
            "status":       self.status,
            "notes":        self.notes,
        }


# ─────────────────────────────────────────────────────────────────────────────
class Notification(db.Model):
    """In-app notifications for the doctor."""
    __tablename__ = "notifications"

    id         = db.Column(db.Integer,     primary_key=True)
    doctor_id  = db.Column(db.Integer,     db.ForeignKey("users.id"), nullable=False, index=True)
    type       = db.Column(db.String(30),  default="info")   # info | warning | success | danger
    title      = db.Column(db.String(120), nullable=False)
    message    = db.Column(db.String(300), nullable=False)
    is_read    = db.Column(db.Boolean,     default=False)
    created_at = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":         self.id,
            "type":       self.type,
            "title":      self.title,
            "message":    self.message,
            "is_read":    self.is_read,
            "created_at": self.created_at.isoformat(),
        }
