from extensions import db
from datetime import datetime


# Workflow statuses aligned with the doctor frontend case lifecycle
WORKFLOW_AI_DONE = "ai_done"
WORKFLOW_DOCTOR_REVIEW = "doctor_review"
WORKFLOW_SUBMITTED_TO_CODER = "submitted_to_coder"
WORKFLOW_CODER_REVIEW = "coder_review"
WORKFLOW_RETURNED_FOR_CORRECTION = "returned_for_correction"
WORKFLOW_RELEASED_TO_PATIENT = "released_to_patient"


# ─────────────────────────────────────────────────────────────────────────────
class ClinicalNote(db.Model):
    """Uploaded clinical document / typed note."""
    __tablename__ = "clinical_notes"

    id             = db.Column(db.Integer,     primary_key=True)
    patient_id     = db.Column(db.Integer,     db.ForeignKey("patients.id"), nullable=False, index=True)
    doctor_id      = db.Column(db.Integer,     db.ForeignKey("users.id"),    nullable=False)
    visit_type     = db.Column(db.String(50),  default="Initial Consultation")

    # Source: file upload OR typed text
    source_type    = db.Column(db.String(10),  default="text")   # text | file
    raw_text       = db.Column(db.Text,        nullable=True)     # typed or extracted text

    # Azure Blob Storage
    file_name      = db.Column(db.String(255), nullable=True)
    blob_url       = db.Column(db.String(500), nullable=True)     # Azure Blob public/SAS URL
    blob_name      = db.Column(db.String(255), nullable=True)     # Unique blob name in container

    # Azure Document Intelligence (OCR)
    ocr_text       = db.Column(db.Text,        nullable=True)

    # Processing options (stored as flags)
    use_soap       = db.Column(db.Boolean,     default=True)
    use_diagnosis  = db.Column(db.Boolean,     default=True)
    use_treatment  = db.Column(db.Boolean,     default=True)
    use_risk       = db.Column(db.Boolean,     default=False)
    model_choice   = db.Column(db.String(30),  default="MediAI Pro")

    processed      = db.Column(db.Boolean,     default=False)
    created_at     = db.Column(db.DateTime,    default=datetime.utcnow)

    # Relationship to summary
    summary        = db.relationship("AISummary", backref="note", uselist=False)

    def note_text(self) -> str:
        return (self.ocr_text or self.raw_text or "").strip()

    def to_dict(self, include_text=False):
        data = {
            "id":          self.id,
            "patient_id":  self.patient_id,
            "visit_type":  self.visit_type,
            "source_type": self.source_type,
            "file_name":   self.file_name,
            "blob_url":    self.blob_url,
            "processed":   self.processed,
            "has_text":    bool(self.note_text()),
            "created_at":  self.created_at.isoformat(),
        }
        if include_text:
            data["raw_text"] = self.raw_text
            data["ocr_text"] = self.ocr_text
        return data


# ─────────────────────────────────────────────────────────────────────────────
class AISummary(db.Model):
    """SOAP note generated by Azure AI Language Service."""
    __tablename__ = "ai_summaries"

    id           = db.Column(db.Integer, primary_key=True)
    note_id      = db.Column(db.Integer, db.ForeignKey("clinical_notes.id"), nullable=False, index=True)
    patient_id   = db.Column(db.Integer, db.ForeignKey("patients.id"),       nullable=False, index=True)
    doctor_id    = db.Column(db.Integer, db.ForeignKey("users.id"),          nullable=False)

    # SOAP sections (stored individually for easy tab rendering)
    subjective   = db.Column(db.Text, nullable=True)
    objective    = db.Column(db.Text, nullable=True)
    assessment   = db.Column(db.Text, nullable=True)
    plan         = db.Column(db.Text, nullable=True)

    # Azure extras
    key_phrases  = db.Column(db.Text,    nullable=True)   # JSON list
    entities     = db.Column(db.Text,    nullable=True)   # JSON list
    risk_score   = db.Column(db.String(10), nullable=True)

    # Doctor → coder workflow
    workflow_status      = db.Column(db.String(40), default=WORKFLOW_DOCTOR_REVIEW)
    coder_return_reason  = db.Column(db.Text,       nullable=True)
    ai_confidence        = db.Column(db.Integer,    nullable=True)
    submitted_at         = db.Column(db.DateTime,   nullable=True)
    updated_at           = db.Column(db.DateTime,   default=datetime.utcnow, onupdate=datetime.utcnow)

    created_at   = db.Column(db.DateTime, default=datetime.utcnow)

    history_events = db.relationship(
        "CaseHistory", backref="summary", lazy="dynamic",
        cascade="all, delete-orphan", order_by="CaseHistory.created_at",
    )

    def to_dict(self, include_history=False):
        import json
        data = {
            "id":          self.id,
            "note_id":     self.note_id,
            "patient_id":  self.patient_id,
            "patient_name": self.patient.name if self.patient else None,
            "visit_type":  self.note.visit_type if self.note else None,
            "subjective":  self.subjective,
            "objective":   self.objective,
            "assessment":  self.assessment,
            "plan":        self.plan,
            "key_phrases": json.loads(self.key_phrases) if self.key_phrases else [],
            "entities":    json.loads(self.entities)    if self.entities    else [],
            "risk_score":  self.risk_score,
            "workflow_status": self.workflow_status,
            "coder_return_reason": self.coder_return_reason,
            "ai_confidence": self.ai_confidence,
            "submitted_at": self.submitted_at.isoformat() if self.submitted_at else None,
            "created_at":  self.created_at.isoformat(),
            "updated_at":  self.updated_at.isoformat() if self.updated_at else None,
        }
        data["has_ai_summary"] = bool(
            (self.subjective or "").strip()
            or (self.objective or "").strip()
            or (self.assessment or "").strip()
            or (self.plan or "").strip()
        )
        if include_history:
            data["history"] = [h.to_dict() for h in self.history_events.all()]
        return data

    def add_history(self, event: str):
        entry = CaseHistory(summary_id=self.id, event=event)
        db.session.add(entry)
        return entry


# ─────────────────────────────────────────────────────────────────────────────
class Appointment(db.Model):
    """Patient appointment."""
    __tablename__ = "appointments"

    id           = db.Column(db.Integer,     primary_key=True)
    patient_id   = db.Column(db.Integer,     db.ForeignKey("patients.id"), nullable=False, index=True)
    doctor_id    = db.Column(db.Integer,     db.ForeignKey("users.id"),    nullable=False)
    title        = db.Column(db.String(150), nullable=False)
    visit_type   = db.Column(db.String(50),  default="Follow-Up")
    scheduled_at = db.Column(db.DateTime,    nullable=False)
    duration_min = db.Column(db.Integer,     default=30)
    status       = db.Column(db.String(20),  default="scheduled")   # scheduled | completed | cancelled
    notes        = db.Column(db.Text,        nullable=True)
    created_at   = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":           self.id,
            "patient_id":   self.patient_id,
            "patient_name": self.patient.name if self.patient else None,
            "title":        self.title,
            "visit_type":   self.visit_type,
            "scheduled_at": self.scheduled_at.isoformat(),
            "duration_min": self.duration_min,
            "status":       self.status,
            "notes":        self.notes,
        }


# ─────────────────────────────────────────────────────────────────────────────
class Notification(db.Model):
    """In-app notifications for the doctor."""
    __tablename__ = "notifications"

    id         = db.Column(db.Integer,     primary_key=True)
    doctor_id  = db.Column(db.Integer,     db.ForeignKey("users.id"), nullable=False, index=True)
    type       = db.Column(db.String(30),  default="info")   # info | warning | success | danger
    title      = db.Column(db.String(120), nullable=False)
    message    = db.Column(db.String(300), nullable=False)
    is_read    = db.Column(db.Boolean,     default=False)
    created_at = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        return {
            "id":         self.id,
            "type":       self.type,
            "title":      self.title,
            "message":    self.message,
            "is_read":    self.is_read,
            "created_at": self.created_at.isoformat(),
        }


# ─────────────────────────────────────────────────────────────────────────────
class CaseHistory(db.Model):
    """Timeline events for a clinical case (summary workflow)."""
    __tablename__ = "case_history"

    id          = db.Column(db.Integer,     primary_key=True)
    summary_id  = db.Column(db.Integer,     db.ForeignKey("ai_summaries.id"), nullable=False, index=True)
    event       = db.Column(db.String(300), nullable=False)
    created_at  = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        return {
            "at":    self.created_at.isoformat(),
            "event": self.event,
        }


# ─────────────────────────────────────────────────────────────────────────────
class AuditLog(db.Model):
    """Immutable audit trail for doctor actions."""
    __tablename__ = "audit_logs"

    id          = db.Column(db.Integer,     primary_key=True)
    doctor_id   = db.Column(db.Integer,     db.ForeignKey("users.id"), nullable=False, index=True)
    action      = db.Column(db.String(80),  nullable=False)
    entity_type = db.Column(db.String(40),  nullable=True)
    entity_id   = db.Column(db.Integer,     nullable=True)
    details     = db.Column(db.Text,        nullable=True)
    created_at  = db.Column(db.DateTime,    default=datetime.utcnow)

    def to_dict(self):
        import json
        return {
            "id":          self.id,
            "actor_id":    self.doctor_id,
            "action":      self.action,
            "entity_type": self.entity_type,
            "entity_id":   self.entity_id,
            "details":     json.loads(self.details) if self.details else None,
            "at":          self.created_at.isoformat(),
        }
